### DISCUSSION TITLE
How to add custom fields?

### DISCUSSION THREAD

**Discussion by shay-legit** [fluent/fluent-operator#1097] [Q&A]
Hi there

Sorry if this is a level-100 thing but I don't see any docs for it - my bad if I missed it.

I am looking to add custom field to our logs before they are shipped.

Specifically these (this is from the raw config of non-operator fluentbit):

```
[FILTER]
        Name            modify
        Match           *
        Add             applicationName ${Application_Name}
        Add             subsystemName ${SubSystem_Name}
        Add             computerName ${HOSTNAME}
```

Current ClusterFilter:

```
apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterFilter
metadata:
  name: custom-filter
  labels:
    fluentbit.fluent.io/enabled: "true"
    fluentbit.fluent.io/mode: "k8s"
spec:
  match: "*"
  filters:
    - nest:
        operation: nest
        wildcard:
          - "*"
        nestUnder: text
    - <add field here?>
```

Any example or suggestions?

Thank you
