### DISCUSSION TITLE
how to add storage.metrics field  for /api/v1/storage

### DISCUSSION THREAD

**Discussion by wangtao208208** [fluent/fluent-operator#1374] [Q&A] [answered]
In fluent-bit doc, Monitoring enable /api/v1/storage:
```
Get internal metrics of the storage layer / buffered data. 
This option is enabled only if in the SERVICE section of the property storage.metrics is enabled.
```

how to add storage.metrics in the following doc?

```
apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterFluentBitConfig
metadata:
  name: fluent-bit-config
  labels:
    app.kubernetes.io/name: fluent-bit
spec:
  service:
    parsersFile: parsers.conf
    httpListen: 0.0.0.0
    httpPort: 2020
    httpServer: true
    healthCheck: true
```

Any example or suggestions?

Thank you

**Comment by wangtao208208** [comment, marked as answer]
```
apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterFluentBitConfig
metadata:
  name: fluent-bit-config
  labels:
    app.kubernetes.io/name: fluent-bit
spec:
  service:
    parsersFile: parsers.conf
    httpListen: 0.0.0.0
    httpPort: 2020
    httpServer: true
    healthCheck: true
    parsersFile: parsers.conf  
    hcErrorsCount: 5
    hcRetryFailureCount: 5
    hcPeriod: 5
    storage:
      metrics: "on"
  inputSelector:
```

it took effect like this.

it take much time for me guess it.  is there any doc for reference?
