### ISSUE TITLE
bug: fluentd elasticsearch output plugin does not propose `ssl_verify` option proposed by the Ruby plugin

### ISSUE THREAD

**Issue by antrema** [fluent/fluent-operator#1010]
### Describe the issue

The fluentd elasticsearch output plugin doesn't propose an option that is supported by the Ruby plugin.
The Ruby plugin propose a `ssl_verify` option to disable SSL/TLS certificate verification (https://github.com/uken/fluent-plugin-elasticsearch#user-password-path-scheme-ssl_verify) whereas the fluentd output plugin does not propose this option

### To Reproduce

Create an `Output` as follow:
```yaml
apiVersion: fluentd.fluent.io/v1alpha1
kind: Output
metadata:
  name: fluentd-es
  namespace: mynamespace
  labels:
    output.fluentd.fluent.io/enabled: "es"
spec: 
  outputs: 
  - elasticsearch:
      host: myelastic.mydomain.com
      port: 9243
      indexName: myindex
      user:
        valueFrom:
          secretKeyRef:
            name: elastic-secret
            key: user
      password:
        valueFrom:
          secretKeyRef:
            name: elastic-secret
            key: password
      scheme: https
```
After applying this output, fluentd pod failed to connect to Elastic Endpoint with following message
```
The client is unable to verify that the server is Elasticsearch. Some functionality may not be compatible if the server is running an unsupported product.
2023-12-07 08:06:57 +0000 [error]: #0 unexpected error error_class=Elastic::Transport::Transport::Error error="SSL_connect returned=1 errno=0 peeraddr=10.xxx.xxx.xxx:9243 state=error: certificate verify failed (self-signed certificate in certificate chain) (OpenSSL::SSL::SSLError) Unable to verify certificate. This may be an issue with the remote host or with Excon. Excon has certificates bundled, but these can be customized:
            `Excon.defaults[:ssl_ca_path] = path_to_certs`
            `ENV['SSL_CERT_DIR'] = path_to_certs`
            `Excon.defaults[:ssl_ca_file] = path_to_file`
            `ENV['SSL_CERT_FILE'] = path_to_file`
            `Excon.defaults[:ssl_verify_callback] = callback`
                (see OpenSSL::SSL::SSLContext#verify_callback)
                or:
            `Excon.defaults[:ssl_verify_peer] = false` (less secure).
```
I cannot disable SSL verification as `verify_ssl` is not proposed

### Expected behavior

To be able to disable SSL/TLS verification

### Your Environment

```markdown
- Fluent Operator version: kubesphere/fluent-operator:v2.6.0
- Container Runtime: containerd://1.7.5
- Operating system: Linux/AMD64
- Kernel version: 5.15.0-90-generic
```

### How did you install fluent operator?

I installed the fluent-operator as described in fluent-operator [documentation](https://github.com/fluent/fluent-operator#deploy-fluent-operator-with-yaml)
```bash
kubectl create ns fluent 
kubectl apply -f https://raw.githubusercontent.com/fluent/fluent-operator/release-2.6/manifests/setup/setup.yaml
```
