### ISSUE TITLE
help request: how to enable tls in ClusterOutput resource for elastic search (es) with fluent bit

### ISSUE THREAD

**Issue by anthonyoride** [fluent/fluent-operator#1012]
### Describe the issue

i am currently unable to enable tls using the ClusterOutput resource for elastic search(es). from the fluent docs https://docs.fluentbit.io/manual/v/1.0/configuration/tls_ssl, tls can be set to On. however, from the fluent operator for ClusterOutput for elastic search(es), the tls field spec from https://github.com/fluent/fluent-operator/blob/master/docs/plugins/fluentbit/tls.md does not have a property for turning on tls.

below is my  ClusterOutput resource for elastic search(es)

apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterOutput
metadata:
  name: k8s-app-es
  labels:
    fluentbit.fluent.io/enabled: "true"
    fluentbit.fluent.io/mode: "k8s"
spec:
  matchRegex: (?:kube|service)\.(.*)
  es:
    host: elastic-search-es-http.elastic-system.svc.cluster.local
    port: 9200
    generateID: true
    index: fluent-bit
    logstashPrefix: fluent-app-log-fb-only
    logstashFormat: true
    timeKey: "@timestamp"
    traceError: true
    replaceDots: true
    type: _doc

**Comment by wenchajun** [comment]
like this
```

kind: Output
metadata:
  annotations:
  labels:
    logging.kubesphere.io/component: events
    logging.kubesphere.io/enabled: 'true'
  name: opensearch-events
  namespace: kubesphere-logging-system
spec:
  match: xxx
  opensearch:
    bufferSize: 20MB
    generateID: true
    host: opensearch-cluster-data.kubesphere-logging-system.svc
    httpPassword:
      valueFrom:
        secretKeyRef:
          key: password
          name: opensearch-credentials
    httpUser:
      valueFrom:
        secretKeyRef:
          key: username
          name: opensearch-credentials
    logstashFormat: true
    logstashPrefix: xxxx
    port: 9200
    suppressTypeName: true
    tls:
      verify: false //true or false
    traceError: true

```
