### ISSUE TITLE
Stackdriver Output support for helm chart 

### ISSUE THREAD

**Issue by UgurcanAkkok** [fluent/fluent-operator#1038]
### Is your feature request related to a problem? Please describe.

I am deploying fluent operator to my GKE cluster, as i need a custom fluentbit deployment. I am using the helm chart with my values.yaml. The relavent fields are as follows:

```
# values.yaml
fluentbit:
  output:
    stackdriver:
      resource: k8s_container
      k8sClusterName: MYCLUSTER
      k8sClusterLocation: MYLOCATION
```
But the resulting output configuration is as follows:
```
# fluent-bit.conf
[Output]
    Name    null
    Match   *
```

### Describe the solution you'd like

I am guessing we need a template file here for stackdriver: https://github.com/fluent/fluent-operator/tree/master/charts/fluent-operator/templates, just like the elasticsearch: https://github.com/fluent/fluent-operator/blob/master/charts/fluent-operator/templates/fluentbit-output-elasticsearch.yaml 

Since the CRDs for output support stackdriver, i think this would be enough ?

As an end user of this chart, i would like to be able to give the stackdriver values in the output field of the values.yaml (as given above).
