### ISSUE TITLE
bug: incorrect fields in syslog input plugin parameters

### ISSUE THREAD

**Issue by lukasboettcher** [fluent/fluent-operator#1083]
### Describe the issue

The fields `Mode, Listen and BufferMaxSize` are not set correctly by the operator.

### To Reproduce

create a syslog input:

```
apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterInput
metadata:
  name: syslog
  labels:
    fluentbit.fluent.io/enabled: "true"
    fluentbit.fluent.io/component: logging
spec:
  syslog:
    mode: tcp
    port: 6659
```

check the generated config:
```
kubectl get secrets fluent-bit-config -o jsonpath='{.data.fluent-bit\.conf}' | base64 -d
```

### Expected behavior

The fields `Mode, Listen and BufferMaxSize` should be present in the config.

### Your Environment

```markdown
- Fluent Operator version: latest
- Container Runtime: v1.7.13
- Operating system: Arch
- Kernel version: 6.7.8
```
