### ISSUE TITLE
Make namespaced rewrite_tag rule key configurable

### ISSUE THREAD

**Issue by alternaivan** [fluent/fluent-operator#1096]
### Is your feature request related to a problem? Please describe.

Hi everyone,

Using the namespaced CRs to deploy specific FluentBit configuration deploys the dynamic Filter similar to below.

```yaml
[Filter]
    Name    rewrite_tag
    Match    kube.*
    Rule    $kubernetes['namespace_name'] ^(test)$ 5236c06addf811b0eaf2fabbd31c89f2.$TAG false
```

This doesn't work in case you have syslog configured as an output, and need to list the nested objects. Check out [this issue](https://github.com/fluent/fluent-bit/issues/5467) for more information.

Looking at the code, we found the below line to be hard-coded.

```go
buf.WriteString(fmt.Sprintf("    Rule    $kubernetes['namespace_name'] ^(%s)$ %x.$TAG false\n", cfg.Namespace, md5.Sum([]byte(cfg.Namespace))))
```
[Source](https://github.com/fluent/fluent-operator/blob/9d10cd98c5dd824305fece48b3fc9ca7cfd552de/controllers/fluentbitconfig_controller.go#L312)

This setting causes the `rewrite_tag` filter not to work properly.

### Describe the solution you'd like

Some possible solution would be somewhat similar to the one used in [this PR](https://github.com/fluent/fluent-operator/pull/1085).

For example:

```yaml
apiVersion: fluentbit.fluent.io/v1alpha2
kind: FluentBitConfig
metadata:
  name: fluent-bit-config
  labels:
    app.kubernetes.io/name: fluent-bit
spec:
  filterSelector:
    matchLabels:
      fluentbit.fluent.io/enabled: "true"
  outputSelector:
    matchLabels:
      fluentbit.fluent.io/enabled: "true"
  parserSelector:
    matchLabels:
      fluentbit.fluent.io/enabled: "true"
  service:
    emitterRuleKey: "kubernetes_namespace_name"
```

Would generate to the below filter.

```yaml
[Filter]
    Name    rewrite_tag
    Match    kube.*
    Rule    $kubernetes_namespace_name ^(test)$ 5236c06addf811b0eaf2fabbd31c89f2.$TAG false
    Emitter_Name    test
```

### Additional context

Some useful links:

- https://docs.fluentbit.io/manual/pipeline/filters/rewrite-tag#key
- https://github.com/fluent/fluent-operator/pull/1085
- https://github.com/fluent/fluent-bit/issues/5467
- https://github.com/fluent/fluent-operator/blob/release-2.7/controllers/fluentbitconfig_controller.go#L312

Thanks,
Marjan
