### ISSUE TITLE
help request: Fluent-Bit installed by fluent-operator is not working

### ISSUE THREAD

**Issue by vi4vikas** [fluent/fluent-operator#1124]
### Describe the issue

I have installed fluent-bit (v2.2.0) in my cluster via fluent-operator (v2.7.0).
But when the fluent-bit pods come up, they don't transport any logs. The only logs that I can see are container CPU usage:
```
[0] cpu.local: [[1713176497.122749350, {}], {"cpu_p"=>3.500000, "user_p"=>1.750000, "system_p"=>1.750000, "cpu0.p_cpu"=>3.000000, "cpu0.p_user"=>1.000000, "cpu0.p_system"=>2.000000, "cpu1.p_cpu"=>3.000000, "cpu1.p_user"=>2.000000, "cpu1.p_sy 
[0] cpu.local: [[1713176498.122623216, {}], {"cpu_p"=>6.500000, "user_p"=>2.500000, "system_p"=>4.000000, "cpu0.p_cpu"=>5.000000, "cpu0.p_user"=>1.000000, "cpu0.p_system"=>4.000000, "cpu1.p_cpu"=>11.000000, "cpu1.p_user"=>5.000000, "cpu1.p_s 
[0] cpu.local: [[1713176499.122677084, {}], {"cpu_p"=>7.250000, "user_p"=>3.250000, "system_p"=>4.000000, "cpu0.p_cpu"=>8.000000, "cpu0.p_user"=>4.000000, "cpu0.p_system"=>4.000000, "cpu1.p_cpu"=>4.000000, "cpu1.p_user"=>2.000000, "cpu1.p_sy 
[0] cpu.local: [[1713176500.122639560, {}], {"cpu_p"=>4.500000, "user_p"=>3.000000, "system_p"=>1.500000, "cpu0.p_cpu"=>4.000000, "cpu0.p_user"=>3.000000, "cpu0.p_system"=>1.000000, "cpu1.p_cpu"=>4.000000, "cpu1.p_user"=>2.000000, "cpu1.p_sy 
[0] cpu.local: [[1713176501.122628069, {}], {"cpu_p"=>5.000000, "user_p"=>2.500000, "system_p"=>2.500000, "cpu0.p_cpu"=>3.000000, "cpu0.p_user"=>1.000000, "cpu0.p_system"=>2.000000, "cpu1.p_cpu"=>7.000000, "cpu1.p_user"=>2.000000, "cpu1.p_sy 
[0] cpu.local: [[1713176502.122605790, {}], {"cpu_p"=>3.750000, "user_p"=>1.750000, "system_p"=>2.000000, "cpu0.p_cpu"=>2.000000, "cpu0.p_user"=>0.000000, "cpu0.p_system"=>2.000000, "cpu1.p_cpu"=>8.000000, "cpu1.p_user"=>5.000000, "cpu1.p_sy 
```
Logs in fluent-operator pods are as:
```
fluent-operator     /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:235                                                                                                                                  
fluent-operator 2024-04-15T10:17:38Z    ERROR    Reconciler error    {"controller": "fluentbit", "controllerGroup": "fluentbit.fluent.io", "controllerKind": "FluentBit", "FluentBit": {"name":"fluent-bit","namespace":"logging"}, "namespace":  
fluent-operator sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler                                                                                                                                             
fluent-operator     /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:329                                                                                                                                  
fluent-operator sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem                                                                                                                                          
fluent-operator     /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:274                                                                                                                                  
fluent-operator sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2                                                                                                                                                
fluent-operator     /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:235                                                                                                                                  
Stream closed EOF for logging/fluent-operator-5bf7f5cfcb-xljph (setenv)                                                                                                                                                                           
```

### How did you install fluent operator?

I have installed fluent-operator by [this](https://github.com/fluent/fluent-operator/tree/v2.7.0/charts/fluent-operator) helm chart. Fluent bit configuration that I am passing in are as:
```
    input:
      tail:
        enable: true
        bufferChunkSize: 1MB
        bufferMaxSize: 1MB
        db: /var/log/flb_kube.db
        excludePath: /var/log/containers/fluentd-cloudwatch*.log,/var/log/containers/snapshot-cb*.log,/var/log/containers/snapshotcreatorrunner*.log
        memBufLimit: 100MB
        multilineParser: cri, docker
        path: "/var/log/containers/*.log"
        pauseOnChunksOverlimit: "off"
        readFromHead: false
        refreshIntervalSeconds: 10
        skipLongLines: true
        storageType: filesystem
        tag: "kube.*"

    output:
      s3:
        Bucket: dev-logs  # Cluster Specific
        CannedAcl: bucket-owner-full-control
        Compression: gzip
        Region: eu-west-1
        RetryLimit: 3
        S3KeyFormat: /logs/%Y/%m/%d/%H/$UUID.gz   # Cluster Specific
        S3KeyFormatTagDelimiters: .-
        StoreDirLimitSize: 2G
        TotalFileSize: 5M
        UploadChunkSize: 1m
        UsePutObject: true

    service:
      daemon: false
      flushSeconds: 10
      healthCheck: true
      httpListen: 0.0.0.0
      httpPort: 2020
      httpServer: true
      logLevel: info
      storage:
        backlogMemLimit: 300Mi
        checksum: "on"
        deleteIrrecoverableChunks: "on"
        maxChunksUp: 1000
        metrics: "on"
        path: "/var/log/fluent-bit-buffer/"
        sync: "full"

    filter:
      kubernetes:
        annotations: false
        bufferSize: "0MB"
        cacheUseDockerId: true
        k8sLoggingExclude: true
        k8sLoggingParser: true
        keepLog: true
        kubeCAFile: "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
        kubeTagPrefix: "kube.var.log.containers."
        kubeTokenFile: "/var/run/secrets/kubernetes.io/serviceaccount/token"
        kubeURL: "https://kubernetes.default.svc:443"
        labels: true
        match: kube.*
        mergeLog: true
        mergeLogKey: log4j
      rewriteTag:
        emitterName: ns_emitter
        rules:
        - "$kubernetes['namespace_name'] ^.*$"
        - "$kubernetes['namespace_name'] false"
```

### Additional context

Other configurations are as:
```
fluent-operator:
  # Configurations for Fluent Operator
  containerRuntime: containerd
  operator:
    initcontainer:
      repository: <docker_image>
      tag: 20.10.8
      resources:
        limits:
          memory: 64Mi
        requests:
          cpu: 50m
          memory: 64Mi

    container:
      repository: "kubesphere/fluent-operator"
      tag: v2.7.0

    priorityClassName: "core-pod-low-priority"

    resources:
      limits:
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 500Mi

    annotations:
      dynamo.certificate.tls/active: "false"

    labels:
      k8s-app: fluent-operator
      version: v1
      kubernetes.io/cluster-service: "true"

    disableComponentControllers: "fluentd"

  # Configurations for Fluent-Bit
  fluentbit:
    image:
      repository: "kubesphere/fluent-bit"
      tag: 2.2.0

    resources:
      limits:
        memory: 300Mi
      requests:
        cpu: 400m
        memory: 300Mi

    labels:
      k8s-app: fluent-bit
      version: v1
      kubernetes.io/cluster-service: "true"

    additionalVolumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers

    additionalVolumesMounts:
      - name: varlog
        mountPath: /var/log
      - name: varlibdockercontainers
        mountPath: /var/lib/docker/containers
        readOnly: true

    tolerations:
      - key: node-role.kubernetes.io/master
        operator: "Exists"
        effect: "NoSchedule"
      - operator: "Exists"
        effect: "NoExecute"
      - operator: "Exists"
        effect: "NoSchedule"

    priorityClassName: "core-pod-low-priority"
  
  fluentd:
    crdsEnable: false
    enable: false

  nameOverride: ""
  fullnameOverride: ""
  namespaceOverride: "logging"
```

Please let me know if any more detail is required.
