### ISSUE TITLE
Fluent bit lua plugin `code` and `script` is not require colume in the same time

### ISSUE THREAD

**Issue by onecer** [fluent/fluent-operator#1128]
### Is your feature request related to a problem? Please describe.

When I define some lua filter like this

```yaml
apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterFilter
metadata:
  name: kubernetes
  labels:
    fluentbit.fluent.io/enabled: "true"
    fluentbit.fluent.io/component: logging
spec:
  match: kube.*
  filters:
  - lua:
      script:
        key: containerd.lua
        name: fluent-bit-containerd-config
      call: add_k8s_app_name_field
      timeAsTable: true
```
I got this error
```
Release "fluent-operator" does not exist. Installing it now.
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(ClusterFilter.spec.filters[0].lua): missing required field "code" in io.fluent.fluentbit.v1alpha2.ClusterFilter.spec.filters.lua
```

I think I use `script` , `code` is not necessary. Or do I use `code` to same my lua script, `script` is necessary.

### Describe the solution you'd like

make `code` and `script` is optional.
