### ISSUE TITLE
multilineparserspec should be embedding structs

### ISSUE THREAD

**Issue by onecer** [fluent/fluent-operator#1131]
### Is your feature request related to a problem? Please describe.

if not use anonymous struct
```
type MultilineParserSpec struct {
	MultilineParser *multilineparser.MultilineParser `json:",inline"`
}
```

then required a manifest like this, and it's wrong , don't match

```yaml
spec:
  MultilineParser:
    flushTimeout: 500
    rules:
    - next: cont
      regex: /^(\d+ \d+\:\d+\:\d+)(.*)/
      start: start_state
    - next: cont
      regex: /^\s+at.*/
      start: cont
    type: regex
```

### Describe the solution you'd like

use anonymous struct 

```yaml
type MultilineParserSpec struct {
	*multilineparser.MultilineParser `json:",inline"`
}
```
