### ISSUE TITLE
bug: Fluent-operator helm chart renders incorrectly the container arguments when operator.disableComponentControllers is set.

### ISSUE THREAD

**Issue by nickytd** [fluent/fluent-operator#1159]
### Describe the issue

`fluent-operator` goes into CrashLoopback when 
```
operator:
  disableComponentControllers: "fluentd"
```
is set.

The error is:
```
2024-05-03T11:17:53Z	ERROR	setup		{"error": "incorrect value for `-disable-component-controllers` and it will not be proceeded (possible values are: fluent-bit, fluentd)"}
main.main
	/workspace/main.go:121
runtime.main
	/usr/local/go/src/runtime/proc.go:267
```

And is due to the incorrect container template
```
args:
  - --disable-component-controllers="fluentd"
```       

The correct value shall be
```
args:
  - "--disable-component-controllers=fluentd"
```   

### To Reproduce

Render the current template with 
```
helm template https://github.com/fluent/fluent-operator/releases/download/v2.8.0/fluent-operator-2.8.0.tgz --set operator.disableComponentControllers=fluentd -s templates/fluent-operator-deployment.yaml
```
It produces:
```
......
        args:
          - --disable-component-controllers="fluentd"
        volumeMounts:
        - name: env
          mountPath: /fluent-operator
      serviceAccountName: fluent-operator
```

### Expected behavior

Shall produce a valid arguments list and fluent-operator pod shall reach Ready state.

### Your Environment

```markdown
- Fluent Operator version: 2.8.0
- Container Runtime: containerd
- Operating system: linux
- Kernel version: 6.8.0
```

### How did you install fluent operator?

Via the helm chart

### Additional context

Fix is provided
