### ISSUE TITLE
serviceAccount should give the option to be self managed

### ISSUE THREAD

**Issue by maor-paz-hs** [fluent/fluent-operator#1184]
### Is your feature request related to a problem? Please describe.

I want to use a custom serviceAccount for the fluent-bit, this is required to grant access to AWS resources, currently only serviceAccountAnnotations is possible.

### Describe the solution you'd like

```
fluentbit:
  serviceAccount:
    create: false
    name: <SomeName>
```
