### ISSUE TITLE
bug: ServiceMonitor doesn't select fluent-bit service

### ISSUE THREAD

**Issue by rmvangun** [fluent/fluent-operator#1292]
### Describe the issue

The helm chart creates a ServiceMonitor with:

```
...
  selector:
    matchLabels:
      app.kubernetes.io/instance: fluent-operator
      app.kubernetes.io/name: fluent-operator
```

However, the actual fluent-bit service has the following:

```
...
  labels:
    app.kubernetes.io/name: fluent-bit
...
```

I believe that the default selector for the ServiceMonitor should match `app.kubernetes.io/name: fluent-bit`

### To Reproduce

Install with the helm chart using default settings and enable the service monitor. Observe the `matchLabels`

### Expected behavior

The default service monitor would match the fluent-bit service labels and so scrape its metrics properly.

### Your Environment

```markdown
- Fluent Operator helm chart version: 3.0.0
```

### How did you install fluent operator?

Helm chart

### Additional context

The root cause is the use of the `fluent-operator.selectorLabels` helper. I believe that the `fluent-bit` service and service monitor need to use their own labels.
