### ISSUE TITLE
Support logs_body_key_attributes in OpenTelemetry output plugin

### ISSUE THREAD

**Issue by LKummer** [fluent/fluent-operator#1321]
### Is your feature request related to a problem? Please describe.

The `logs_body_key_attributes` of the OpenTelemetry output plugin is not yet supported by the operator. It was added in https://github.com/fluent/fluent-bit/commit/202da1374dffd98984b2aa56dd444d49bef1dbd5.

I've been using the custom plugin option to enable it, and would like to have it supported by the output plugin CRDs.

```yaml
apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterOutput
# ...
spec:
  customPlugin:
    config: |
      name opentelemetry
      match kube.*
      host telemetry-exporter-components-collector
      port 4318
      logs_body_key_attributes true
  matchRegex: kube\.(.*)
```

### Describe the solution you'd like

Add `logsBodyKeyAttributes` to OpenTelemetry output plugin schema.

I'd love to contribute the change, and will soon shoot a PR for it.
