### ISSUE TITLE
bug: fluent-bit flushSeconds should support fractional values

### ISSUE THREAD

**Issue by jjsiv** [fluent/fluent-operator#1405]
### Describe the issue

It is currently not possible to use fractional values for flushSeconds, e.g 0.1s. My suggestion is to change it to float. This shouldn't break backwards compatibility

### To Reproduce

```yaml
apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterFluentBitConfig
metadata:
  name: fluent-bit-config
spec:
  inputSelector:
    matchLabels:
      fluentbit.fluent.io/enabled: "true"
  outputSelector:
    matchLabels:
      fluentbit.fluent.io/enabled: "true"
  service:
    flushSeconds: 0.1
```

### Expected behavior

ClusterFluentBitConfig supports fractional values for flushSeconds

### Your Environment

```markdown
- Fluent Operator version:
- Container Runtime:
- Operating system:
- Kernel version:
```

### Additional context

Even though official fluent-bit docs describe the value for Flush as int type, it is in fact a double
https://github.com/fluent/fluent-bit/blob/master/include/fluent-bit/flb_config.h#L49
