### ISSUE TITLE
bug: Fluent Bit custom docker image issue

### ISSUE THREAD

**Issue by sjanorkar** [fluent/fluent-operator#1414]
### Describe the issue

Even after specifying custom docker image for fluent bit, default image is being used in the fluent-bit pods.

Fluentbit daemonset configuration
```
apiVersion: fluentbit.fluent.io/v1alpha2
kind: FluentBit
metadata:
  name: fluent-bit
  namespace: fluent
  labels:
    app.kubernetes.io/name: fluent-bit
spec:
  {{- with .Values.fluentbit.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  image: eu.gcr.io/sap-ml-mlf-dev/com.sap.aicore/fluent-operator-fluentbit:3.1.7-sap0
  {{- with .Values.fluentbit.imagePullSecrets }}
  imagePullSecrets:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  imagePullPolicy: {{ .Values.fluentbit.imagePullPolicy }}
  positionDB:
    hostPath:
      path: /var/lib/fluent-bit/
  resources:
    requests:
      cpu: {{ .Values.fluentbit.requests.cpu }}
      memory: {{ .Values.fluentbit.requests.memory }}
    limits:
      cpu: {{ .Values.fluentbit.limits.cpu }}
      memory: {{ .Values.fluentbit.limits.memory }}
  fluentBitConfigName: fluent-bit-only-config
  tolerations:
    - operator: Exists
```

Actual fluentbit daemonset pod
![Screenshot 2024-11-20 at 2 41 39 PM](https://github.com/user-attachments/assets/acbad961-d205-4d48-9ca0-0e6e487eb752)

### To Reproduce

1. Use custom docker image for FluentBit 
2. Create a fluent-bit daemon set 

### Expected behavior

Fluent bit pods should be created with the custom docker image.

### Your Environment

```markdown
- Fluent Operator version: 3.1.0
- Container Runtime: docker
- Operating system: linux
- Kernel version: 6.6.35-cloud-amd64
```
