### ISSUE TITLE
bug: Loki output labelKeys not formatting correctly

### ISSUE THREAD

**Issue by heytrav** [fluent/fluent-operator#1508]
### Describe the issue

When attempting to define `labelKeys` under `fluentbit.output.loki` the attribute is prepended to the previous section and the helm fails to render.

I've been trying to define the labelKeys as follows

```
    fluentbit:
  
      output:
        loki:
          enable: true
  
          labelKeys:
            - kubernetes.namespace_name
            - kubernetes.pod_name

```

Helm is returning an error:
```
Error: YAML parse error on fluent-operator/templates/fluentbit-output-loki.yaml: error converting YAML to JSON: yaml: line 26: mapping values are not allowed in this context
helm.go:86: 2025-03-19 16:06:47.153355 +1300 NZDT m=+1.323365417 [debug] error converting YAML to JSON: yaml: line 26: mapping values are not allowed in this context
```

### To Reproduce

If I try to render the fluent-operator template in the command line to see what output is being generated 

```
helm template fluent fluent/fluent-operator --set fluentbit.output.loki.enable=true --set fluentbit.output.loki.labelKeys.0=kubernetes.container_name
```

The templated output looks like this:
```
   httpPassword:
      valueFrom:
        secretKeyRef:
          key: 'value'
          name: loki-http-pass
          optional: falselabelKeys:
      "0": kubernetes.container_name
```

It looks like the code that renders the fluentbit loki output [here](https://github.com/fluent/fluent-operator/blob/a4180d4128ff73b40619f3b561526b027a3930cf/charts/fluent-operator/templates/fluentbit-output-loki.yaml#L117-L121) is failng to put a newline before the `labelKeys` is rendered.

Interestingly if I add a `labels=` as well it comes out looking more like I expect:

```
helm template fluent fluent/fluent-operator --set fluentbit.output.loki.enable=true --set fluentbit.output.loki.labelKeys.0=kubernetes.container_name --set fluentbit.output.loki.labelKeys.1=kubernetes.namespace_name --set fluentbit.output.loki.labels.0=test=test
```

```
    httpPassword:
      valueFrom:
        secretKeyRef:
          key: 'value'
          name: loki-http-pass
          optional: false
    labels:
      "0": test=test
    labelKeys:
      "0": kubernetes.container_name
      "1": kubernetes.namespace_name
```

### Expected behavior

The `labelKeys` section renders correctly when I pass a list of items to it.

### Your Environment

```markdown
- Fluent Operator version: 3.3.0
- Container Runtime: containerd
- Operating system: Kubernetes 1.32
- Kernel version:
```

### How did you install fluent operator?

FluxCD HelmRelease

example:
```
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fluent-operator
  namespace: flux-system
spec:
  chart:
    spec:
      chart: fluent-operator
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: fluent
      version: '>=3.3.0 < 4.0.0'
  install:
    crds: Create
    createNamespace: true
  interval: 1m0s
  targetNamespace: monitoring
  upgrade:
    crds: CreateReplace
  values:
    fluentbit:
      filter:
        multiline:
          enable: true
        kubernetes:
          labels: true
      output:
        loki:
          enable: true
          host: monitoring-lgtm-loki-gateway.monitoring.svc.cluster.local
          uri: /loki/api/v1/push
          port: 80
          autoKubernetesLabels: on
          compress: gzip
          labels: 
            - this=hack
          labelKeys:
            - kubernetes.namespace_name
            - kubernetes.pod_name


```

### Additional context

I'm actually just trying to get the labels for `kubernetes.namespace_name` and `kubernetes.pod_name`. The documentation is a little short on practical examples for how that should be formatted.

```
{
    "log": "2025-03-17T21:25:39.84794658Z stderr F [2025-03-17 21:25:39,847] [DEBUG] blah ",
    "kubernetes": {
        "pod_name": "some-pod-67b9fdd755-95bq2",
        "namespace_name": "my-namespace",
        "labels": {
            "app.kubernetes.io/instance": "some-pod-name",
            "app.kubernetes.io/managed-by": "Helm",
            "app.kubernetes.io/name": "auth",
            "app.kubernetes.io/version": "0.0.1",
            "helm.sh/chart": "my-helm-chart-v0.0.10-rc.4",
            "pod-template-hash": "67b9fdd755"
        },
        "pod_ip": "10.244.9.167",
        "container_name": "my-container",
        "docker_id": "6............788e6",
        "container_image": "hub.docker.io/nginx"
    }
}

```
