### ISSUE TITLE
Fluentbit does not work when configFileFormat is set to yaml

### ISSUE THREAD

**Issue by truongnht** [fluent/fluent-operator#1553]
When deploying the helmchart with `configFileFormat: yaml` our Fluentbit pod crashes with the following error

![Image](https://github.com/user-attachments/assets/7a09ab3d-714b-4d1e-b3c4-24429141ebac)

paritial fluent-bit config in secret

![Image](https://github.com/user-attachments/assets/e5858958-c81c-47cb-91c2-2a6b6a0067f9)

Please let me know if further information is needed.

**Comment by cw-Guo** [comment]
I was able to reproduced the issue. It's related to this upstream issue: https://github.com/fluent/fluent-bit/issues/9508. 
To fix it, we need to support the latest yaml config file with parser support. https://github.com/fluent/fluent-bit/pull/9513

the following config won't work due to this issue.

```
apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterFluentBitConfig
metadata:
  name: fluentbitconfig-sample
  namespace: fluent
spec:
  service:
    daemon: false
    logLevel: info
    parsersFiles: 
      - parsers.conf
      - parsers_multiline.conf
  inputSelector:
    matchExpressions:
      - key: fluentbit.fluent.io/enabled
        operator: In
        values: ["true"]
  filterSelector:
    matchExpressions:
      - key: fluentbit.fluent.io/enabled
        operator: In
        values: ["true"]
  outputSelector:
    matchExpressions:
      - key: fluentbit.fluent.io/enabled
        operator: In
        values: ["true"]
  configFileFormat: yaml
```

but the following will work:

```
apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterFluentBitConfig
metadata:
  name: fluentbitconfig-sample
  namespace: fluent
spec:
  service:
    daemon: false
    logLevel: info
    parsersFile: parsers.conf
  inputSelector:
    matchExpressions:
      - key: fluentbit.fluent.io/enabled
        operator: In
        values: ["true"]
  filterSelector:
    matchExpressions:
      - key: fluentbit.fluent.io/enabled
        operator: In
        values: ["true"]
  outputSelector:
    matchExpressions:
      - key: fluentbit.fluent.io/enabled
        operator: In
        values: ["true"]
  configFileFormat: yaml
```
