### ISSUE TITLE
bug: resource not been full cleaned after using helm uninstall

### ISSUE THREAD

**Issue by liolay** [fluent/fluent-operator#1583]
### Describe the issue

im using helm install fluent-operator, and after helm uninstall it ,operator removed first, pod which name start with fluent-bit is still keeps running, seems Own Ref (DaemonSet) not works as expected

### To Reproduce

helm install...
all pods running...
helm uninstall...
fluent-operator been removed,and fluent-bit pods keeps running
helm install....
fluent-bit pods removed

### Expected behavior

all resources should been cleared after helm charts be uninstalled

### Your Environment

```markdown
- Fluent Operator version:
- Container Runtime:
- Operating system:
- Kernel version:
```

**Comment by cw-Guo** [comment]
I am not familiar with helm uninstall, but to uninstall all stuffs, you have to make sure the operator pod itself is running when deleting the other custom resources. The operator itself should be deleted at the last.

**Comment by liolay** [comment]
> I am not familiar with helm uninstall, but to uninstall all stuffs, you have to make sure the operator pod itself is running when deleting the other custom resources. The operator itself should be deleted at the last.

according to fluent-operator code[/ #fluentbit_controller](https://github.com/fluent/fluent-operator/blob/4948adc090b4ba90c0b218ece6234c0d02946db1/controllers/fluentbit_controller.go#L331), all daemonsets should be cleaned automated after operator be uninstalled, but when checked daemonset.apps/fluent-bit, i found there's not own reference

**Comment by liolay** [comment]
> I am not familiar with helm uninstall, but to uninstall all stuffs, you have to make sure the operator pod itself is running when deleting the other custom resources. The operator itself should be deleted at the last.

currently,we defined a clean job and annotated it with helm hook
```yaml
{{- if .Values.operator.enable }}
apiVersion: batch/v1
kind: Job
metadata:
  name: pre-delete-fluent-bit-hook
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      serviceAccountName: fluent-operator
      containers:
        - name: cleanup
          image: {{.Values.cleanImage}}
          imagePullPolicy: IfNotPresent
          command:
            - "kubectl"
            - "delete"
            - "FluentBit"
            - "fluent-bit"
            - "--namespace={{ .Release.Namespace }}"
      restartPolicy: Never
{{- end }}
```
