### ISSUE TITLE
bug: keyDoesNotExist of FluentBit ClusterFilter should be a string and not a map

### ISSUE THREAD

**Issue by g1franc** [fluent/fluent-operator#1639]
### Describe the issue

The field of the FluentBit ClusterFilter should be a String as FluentBit expect a String and not a Map[String](String)
https://docs.fluentbit.io/manual/pipeline/filters/modify

Similar FluentBit fields are using a String while other complex fiels are using a Map, as FluentBit expect for them

### To Reproduce

Try to create a 

Try to set a _modify_ rule with using _keyDoesNotExist_  as below

```
    - modify:
        conditions:
          - keyDoesNotExist: mykey
```
It will fail because  it expect a map<String,String>

Guess: Current accepted format should be similar to 

```
    - modify:
        conditions:
          - keyDoesNotExist: 
             - mykey: valuethatisnotrelevant
             - anotherkey: withAnotherValueThatIsUseless
```

### Expected behavior

Setting a _modify_ rule with using _keyDoesNotExist_ should accept below format instead:
```
    - modify:
        conditions:
          - keyDoesNotExist: mykey
```

### Your Environment

```markdown
- Fluent Operator version: 3.4.0 and sooner (at least 3.0.0)
- Container Runtime: N/A
- Operating system: N/A
- Kernel version: N/A
```

### How did you install fluent operator?

By using Helm chart template rendering and apply the produced yaml with ArgoCD.

### Additional context

CRDs, code and Manual page should be adapted to support a single string instead of a map.
