### ISSUE TITLE
bug: Error: template: ...templates/fluentd-fluentd.yaml:17:59: executing "---/templates/fluentd-fluentd.yaml" at <.Values.fluentd.image>: nil pointer evaluating interface {}.fluentd

### ISSUE THREAD

**Issue by BacLuc** [fluent/fluent-operator#1648]
### Describe the issue

When i try to deploy
https://github.com/ecamp/ecamp3/tree/06ebdf63f0708fad42e12393586e68671fafd12b/.ops/ecamp3-logging
i get the following error:
`Error: template: ecamp3-logging/charts/fluent-operator/templates/fluentd-fluentd.yaml:17:59: executing "ecamp3-logging/charts/fluent-operator/templates/fluentd-fluentd.yaml" at <.Values.fluentd.image>: nil pointer evaluating interface {}.fluentd`

with version 3.4.0.
version 3.3.0 worked fine.

And the default of the chart defines a fluentd.image value....?

The deployment action can be found here:
https://github.com/ecamp/ecamp3/blob/06ebdf63f0708fad42e12393586e68671fafd12b/.github/workflows/deploy-ecamp3-logging.yml

### To Reproduce

Deploy the chart with the following values:

```
fluent-operator:
  containerRuntime: containerd
  operator: 
    annotations: 
      trigger-recreate: 7e1048bc-dde1-4bb0-bca5-bba023c62f90
    container: 
      tag: 3.3.0
  fluentbit:
    enable: true
    input:
      tail:
        enable: true
      systemd:
        enable: false
    filter:
      kubernetes:
        labels: true
        annotations: true
    output:
      stdout: 
        # enable to debug fluentbit
        enable: false
  fluentd:
    watchedNamespaces:
      - default
      - ingress-nginx
    envVars: 
      - name: TRIGGER_FLUENTD_RECREATE
        value: 7e1048bc-dde1-4bb0-bca5-bba023c62f90
    enable: true
```

### Expected behavior

The chart can be deployed.

### Your Environment

```markdown
- Fluent Operator version: 3.4.0
- Container Runtime: 
- Operating system:
- Kernel version:
```

### How did you install fluent operator?

As a dependency to my helm chart.
