### ISSUE TITLE
Helm Chart 1.0.2: fluent-bit: unknown configuration property 'DB.Sync'

### ISSUE THREAD

**Issue by hostalp** [fluent/fluent-operator#295]
### Describe the bug

When 1.0.2 is installed from Helm chart, fluent-bit pods error out with:
```
unknown configuration property 'DB.Sync'. The following properties are allowed: path, max_fields, max_entries, systemd_filter_type, systemd_filter, read_from_tail, lowercase, strip_underscores, db_sync, and db
```
And they don't work properly then.
I quickly tested 1.0.1 and it also appears to be affected.
No such issue with 1.0.0

### To Reproduce

Deploy 1.0.2 as follows:
```
helm upgrade --install fluent-operator --create-namespace -n logging https://github.com/fluent/fluent-operator/releases/latest/download/fluent-operator.tgz -f fluent-operator-values.yaml
```
with **fluent-operator-values.yaml**:
```
containerRuntime: docker
Kubernetes: true

operator:
  resources:
    limits:
      cpu: 100m
      memory: 100Mi
    requests:
      cpu: 10m
      memory: 20Mi

fluentbit:
  resources:
    limits:
      cpu: 500m
      memory: 200Mi
    requests:
      cpu: 10m
      memory: 25Mi
  input:
    tail:
      memBufLimit: 10MB

fluentd:
  enable: true
  replicas: 1
  forward:
    host: "logging.svc"
  watchedNamespaces:
    - kube-system
  resources:
    limits:
      cpu: 1000m
      memory: 256Mi
    requests:
      cpu: 20m
      memory: 64Mi
  output:
    es:
      enable: true
      host: logs.local.loc
      port: 9200
      logstashPrefix: k8s_logs_dev
      buffer:
        enable: true
        type: file
        path: /buffers/es

```

### Expected behavior

fluent-bit pods starting without issues

### Your Environment

```markdown
- Fluent Operator version: Helm Chart 1.0.2
- Container Runtime: docker, Kubernetes 1.20.11
```

### How did you install fluent operator?

helm upgrade --install fluent-operator --create-namespace -n logging https://github.com/fluent/fluent-operator/releases/latest/download/fluent-operator.tgz -f fluent-operator-values.yaml

### Your Error Log

```shell
[error] [config] systemd: unknown configuration property 'DB.Sync'. The following properties are allowed: path, max_fields, max_entries, systemd_filter_type, systemd_filter, read_from_tail, lowercase, strip_underscores, db_sync, and db.
```
