### ISSUE TITLE
Support for alias of a plugin

### ISSUE THREAD

**Issue by koenekle** [fluent/fluent-operator#356]
### Is your feature request related to a problem? Please describe.

Currently we are using the [alias feature](https://docs.fluentbit.io/manual/administration/monitoring#configuring-aliases) of fluent-bit, to reference fluent-bit plugin metrics within custom dashboards. Unfortunately this is not possible with fluent-operator.

To us, this is especially important, as we cannot be sure which index a plugin will get, as the order of plugins - and therefore their index - is managed by fluent-operator.

### Describe the solution you'd like

I would like to be able to set the alias like this: 

```
apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterFilter
metadata:
  name: throttle-application-xy
spec:
  match: application.xy
  filters:
    - throttle:
        alias: throttle.application-xy
        rate: 200
        window: 300
        interval: 1s
```

which would result in such a configuration block for fluent-bit:
```
[Filter]
   Name    throttle
   Match   application.xy
   Alias   throttle.application-xy
   Rate    200
   Window  300
   Interval 1s
```

### Additional context

I would be happy to help out implementing this. Please let me know, if I should create a PR.
