### ISSUE TITLE
bug: Can't stdout

### ISSUE THREAD

**Issue by 666MrFang** [fluent/fluent-operator#373]
### Describe the issue

i added an output yaml file,want to stdout logs.i don't know why there will be routing.And when i echo " curl -X POST -H 'Content-Type: multipart/form-data' -F 'json={"message":"foo+bar"}' http://172.16.0.13:9880/app.log",there has nothing in the fluentd container's log,i think it's a problem. I don't understand why there is this problem with helm installation, and why there is a route, and the route does not take effect

```
apiVersion: fluentd.fluent.io/v1alpha1
kind: ClusterOutput
metadata:
  name: fluentd-output-file
  namespace: {{ .Values.namespaceOverride }}
  labels:
    output.fluentd.fluent.io/enabled: "true"
spec:
  outputs:
    - stdout: {}
```
```
<source>
  @type  forward
  bind  0.0.0.0
  port  24224
</source>
<source>
  @type  http
  bind  0.0.0.0
  body_size_limit  32MB
  port  9880
</source>
<match **>
  @id  main
  @type  label_router
  <route>
    @label  @6fd6a7dc1711578c1fbfaf82d231e232
    <match>
      namespaces  default,fst-manage,kube-system
    </match>
  </route>
</match>
<label @6fd6a7dc1711578c1fbfaf82d231e232>
  <match **>
    @id  ClusterFluentdConfig-cluster-fluentd-config::cluster::clusteroutput::fluentd-output-file-0
    @type  stdout
  </match>
</label>
```

### To Reproduce

yaml：
```
apiVersion: fluentd.fluent.io/v1alpha1
kind: ClusterOutput
metadata:
  name: fluentd-output-file
  namespace: {{ .Values.namespaceOverride }}
  labels:
    output.fluentd.fluent.io/enabled: "true"
spec:
  outputs:
    - stdout: {}
```

fluentd config:
```
<source>
  @type  forward
  bind  0.0.0.0
  port  24224
</source>
<source>
  @type  http
  bind  0.0.0.0
  body_size_limit  32MB
  port  9880
</source>
<match **>
  @id  main
  @type  label_router
  <route>
    @label  @6fd6a7dc1711578c1fbfaf82d231e232
    <match>
      namespaces  default,fst-manage,kube-system
    </match>
  </route>
</match>
<label @6fd6a7dc1711578c1fbfaf82d231e232>
  <match **>
    @id  ClusterFluentdConfig-cluster-fluentd-config::cluster::clusteroutput::fluentd-output-file-0
    @type  stdout
  </match>
</label>
```

### Expected behavior

there will has something in logs

### Your Environment

```markdown
- Fluent Operator version: latest
- Container Runtime: docker
- Operating system: linux 
- Kernel version: Linux version 4.18.0-147.5.2.7.h838
```
