### ISSUE TITLE
bug: YAML parse error when rendering templates/fluentbit-fluentBit.yaml

### ISSUE THREAD

**Issue by rothwerx** [fluent/fluent-operator#457]
### Describe the issue

When setting `Kubernetes: true` and populating a values.yaml for fluentbit with more than one annotation, secret, or a volume or volumeMount, the template gets rendered with an extra indent on the first line, causing a parse error. 

Example:
```
  annotations:
      prometheus.io/path: /api/v1/metrics/prometheus
    prometheus.io/port: "2020"
    prometheus.io/scrape: "true"
```

### To Reproduce

In values.yaml fluentbit section, add more than one annotation, volume or volumeMount:
```
Kuberntes: true

<snip>

fluentbit:
  image:
    repository: "kubesphere/fluent-bit"
    tag: "v1.9.9"
  resources:
    limits:
      cpu: 500m
      memory: 200Mi
    requests:
      cpu: 10m
      memory: 25Mi
  # Specify custom annotations to be added to each FluentBit pod.
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '2020'
    prometheus.io/path: '/api/v1/metrics/prometheus'
  imagePullSecrets: [ ]
  # - name: "image-pull-secret"
  secrets: [ ]
  volumes:
    - name: hostProc
      hostPath:
        path: /proc/
    - name: hostSys
      hostPath:
        path: /sys/
    - name: hostContainers
      hostPath:
        path: /var/lib/docker/containers
    - name: hostPods
      hostPath:
        path: /var/log/pods
  volumesMounts:
    - mountPath: /host/sys
      mountPropagation: HostToContainer
      name: hostSys
      readOnly: true
    - mountPath: /host/proc
      mountPropagation: HostToContainer
      name: hostProc
      readOnly: true
    - mountPath: /var/log/pods
      mountPropagation: HostToContainer
      name: hostPods
      readOnly: true
    - mountPath: /var/lib/docker/containers
      mountPropagation: HostToContainer
      name: hostContainers
      readOnly: true
</snip>
```

Then try to install with helm:
```
$ helm install fluent-operator -n fluent --values yaml/values.yaml --version 1.6.1 https://github.com/fluent/fluent-operator/releases/download/v1.6.1/fluent-operator.tgz
Error: INSTALLATION FAILED: YAML parse error on fluent-operator/templates/fluentbit-fluentBit.yaml: error converting YAML to JSON: yaml: line 31: did not find expected '-' indicator
```

### Expected behavior

Template renders correctly and all objects get created with expected values.

### Your Environment

```markdown
- Fluent Operator version: 1.6.1
- Container Runtime: containerd
- Operating system: Ubuntu 20.04.3 LTS
- Kernel version: 5.4.0-97-generic
```

### How did you install fluent operator?

* Pulumi `helm.v3.Release` object
* helm

### Additional context

This problem existed as far back as v1.1.0 but at that time the template only supported secrets and annotations.
