### ISSUE TITLE
help request: fluent-operator: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by wgh9626** [fluent/fluent-operator#485]
### Describe the issue

```yaml
cat fluentd.yaml
apiVersion: fluentd.fluent.io/v1alpha1
kind: Fluentd
metadata:
  name: fluentd
  namespace: fluent
  labels:
    app.kubernetes.io/name: fluentd
spec:
  globalInputs:
  - forward:
      bind: 0.0.0.0
      port: 24224
  replicas: 1
  image: kubesphere/fluentd:v1.14.4
  fluentdCfgSelector:
    matchLabels:
      config.fluentd.fluent.io/enabled: "true"
  buffer:
    hostPath:
      path: "/var/log/fluentd-buffer"
---
apiVersion: fluentd.fluent.io/v1alpha1
kind: ClusterFluentdConfig
metadata:
  name: cluster-fluentd-config
  labels:
    config.fluentd.fluent.io/enabled: "true"
spec:
  watchedNamespaces:
  - kube-system
  - default
  - fluent
  - elastic
  - cattle-prometheus
  - icu
  - ingress-nginx
  - local-path-storage
  - longhorn-system
  - prod
  clusterFilterSelector:
    matchLabels:
      filter.fluentd.fluent.io/type: "buffer"
      filter.fluentd.fluent.io/enabled: "true"
  clusterOutputSelector:
    matchLabels:
      output.fluentd.fluent.io/scope: "cluster"
      output.fluentd.fluent.io/enabled: "true"
---
apiVersion: fluentd.fluent.io/v1alpha1
kind: ClusterFilter
metadata:
  name: cluster-fluentd-filter-buffer
  labels:
    filter.fluentd.fluent.io/type: "buffer"
    filter.fluentd.fluent.io/enabled: "true"
spec:
  filters:
  - recordTransformer:
      enableRuby: true
      records:
      - key: kubernetes_ns
        value: ${record["kubernetes"]["namespace_name"]}
---
apiVersion: fluentd.fluent.io/v1alpha1
kind: ClusterOutput
metadata:
  name: cluster-fluentd-output-es
  labels:
    output.fluentd.fluent.io/scope: "cluster"
    output.fluentd.fluent.io/enabled: "true"
spec:
  outputs:
  - elasticsearch:
      host: elasticsearch-master.elastic.svc
      port: 9200
      password:
        valueFrom:
          secretKeyRef:
            name: elasticsearch-password
            key: ES_PASSWORD
      user:
        valueFrom:
          secretKeyRef:
            name: elasticsearch-password
            key: ES_USER
      logstashFormat: true
      logstashPrefix: fluent-log
    buffer:
      type: file
      path: /buffers/es_buffer
---
apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-password
  namespace: fluent
data:
  ES_PASSWORD: S2dRemR5N1JkRlJKUHRWQg==
  ES_USER: ZWxhc3RpYw==
type: Opaque

```
When I apply -f fluentd.yaml, the fluent-operaor log reports an error:
```shell
Observed a panic in reconciler: runtime error: invalid memory address or nil pointer dereference	{"controller": "fluentd", "controllerGroup": "fluentd.fluent.io", "controllerKind": "Fluentd", "Fluentd": {"name":"cluster-fluentd-output-es"}, "namespace": "", "name": "cluster-fluentd-output-es", "reconcileID": "49e31186-0c68-46a7-8793-974dcad179fb"}
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x14108cb]
goroutine 555 [running]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:118 +0x1f4
panic({0x1562d20, 0x245b570})
	/usr/local/go/src/runtime/panic.go:884 +0x212
github.com/fluent/fluent-operator/controllers.(*FluentdConfigReconciler).ClusterCfgsForFluentd(0xc000533c20, {0x1981178, 0xc000a57440}, {{{0x0, 0x0}, {0x0, 0x0}}, {{0x0, 0x0}, {0x0, ...}, ...}, ...}, ...)
	/workspace/controllers/fluentdconfig_controller.go:267 +0x9cb
github.com/fluent/fluent-operator/controllers.(*FluentdConfigReconciler).Reconcile(0xc000533c20, {0x1981178, 0xc000a57440}, {{{0x0, 0x0}, {0xc000131540, 0x19}}})
	/workspace/controllers/fluentdconfig_controller.go:149 +0x7a5
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0x19810d0?, {0x1981178?, 0xc000a57440?}, {{{0x0?, 0x16704e0?}, {0xc000131540?, 0x4045d4?}}})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:121 +0xc8
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0004848c0, {0x19810d0, 0xc000782580}, {0x15b7460?, 0xc00069bae0?})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:320 +0x33c
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0004848c0, {0x19810d0, 0xc000782580})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:273 +0x1d9
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:234 +0x85
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:230 +0x333
```

How can I solve this problem?

### How did you install fluent operator?

helm fluent-operator-1.7.0
