### ISSUE TITLE
bug: missing authentication credentials for REST request

### ISSUE THREAD

**Issue by tanmx** [fluent/fluent-operator#494]
### Describe the issue

I use fluentd output to es:
```
 output:
    es:
      enable: true
      host: xxxxx
      port: 34435
      logstashPrefix: k8s-logstash-log
      logstashFormat: true
      user: elastic
      password: xxxxx
      buffer:
        enable: false
        type: file
        path: /buffers/es
    opensearch:
      enable: false
```
then the fluentd pod log
```
2022-12-26 06:23:12 +0000 [warn]: #0 [ClusterFluentdConfig-cluster-fluentd-config::cluster::clusteroutput::fluentd-output-es-0] Could not communicate to Elasticsearch, resetting connection and trying again. [401] {"error":{"root_cause":[{"type":"security_exception","reason":"missing authentication credentials for REST request [/]","header":{"WWW-Authenticate":"Basic realm=\"security\" charset=\"UTF-8\""}}],"type":"security_exception","reason":"missing authentication credentials for REST request [/]","header":{"WWW-Authenticate":"Basic realm=\"security\" charset=\"UTF-8\""}},"status":401}
```
get the secret of fluebtd conf. there is no user and password
```
<source>
  @type  forward
  bind  0.0.0.0
  port  24224
</source>
<match **>
  @id  main
  @type  label_router
  <route>
    @label  @cde8d7e07bb996cb240c5ea09e6f80ed
    <match>
      namespaces  default,kube-system,logging
    </match>
  </route>
</match>
<label @cde8d7e07bb996cb240c5ea09e6f80ed>
  <match **>
    @id  ClusterFluentdConfig-cluster-fluentd-config::cluster::clusteroutput::fluentd-output-es-0
    @type  elasticsearch
    host  xxxxx
    logstash_format  true
    logstash_prefix  k8s-logstash-log
    port  34435
    <buffer>
      @type  file
      path  /buffers/es
    </buffer>
  </match>
</label>
```

### To Reproduce

kubectl logs -f fluentd-0 -n logging

### Expected behavior

correct connect to the es

### Your Environment

```markdown
- Fluent Operator version: v1.7.0
- Container Runtime: docker
- Operating system: arm64
- Kernel version: 4.19.90-23.6.v2101.ky10.aarch64
```

### How did you install fluent operator?

helm upgrade --install --wait --create-namespace \
                        --namespace logging -f fluent-values.yaml fluent-operator fluent-operator-v1.7.0.tgz

```
#fluent-values.yaml

fluentd:
  enable: true
  name: fluentd
  port: 24224
  image:
    repository: "dockerhub.kubekey.local/lovelonger/fluentd"
    tag: "v1.15.3-arm64"
  replicas: 1
  forward:
    port: 24224
  watchedNamespaces:
    - kube-system
    - logging
    - default
  resources: {}
  limits:
    cpu: 4
    memory: 4096Mi
  # requests:
    # cpu: 100m
    # memory: 128Mi
  #Configure the output plugin parameter in Fluentd.
  #You can set enable to true to output logs to the specified location.
  output:
    es:
      enable: true
      host: xxxx
      port: 34435
      logstashPrefix: k8s-logstash-log
      logstashFormat: true
      user: elastic
      password: xxxxx
      buffer:
        enable: false
        type: file
        path: /buffers/es
    opensearch:
      enable: false
```
