### ISSUE TITLE
add compress in fluentbit output es

### ISSUE THREAD

**Issue by luckqk** [fluent/fluent-operator#511]
### Is your feature request related to a problem? Please describe.

fluentbit support compress payload in es output  
 (https://docs.fluentbit.io/manual/pipeline/outputs/elasticsearch)[https://docs.fluentbit.io/manual/pipeline/outputs/elasticsearch].   
Will it be supported in operator in the future?

### Describe the solution you'd like

like configuration below
```
----
apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterOutput
metadata:
  labels:
    fluentbit.fluent.io/enabled: "true"
    fluentbit.fluent.io/mode: "fluentbit-only"
  name: es
spec:
  es:
     compress: gzip
```
