### ISSUE TITLE
Can FluentBit CRDs be namespaced?

### ISSUE THREAD

**Issue by alternaivan** [fluent/fluent-operator#516]
### Describe the issue

Hello,

I'm trying to deploy ClusterOutput and ClusterParser to the specific namespace where the FluentBit Operator is deployed, the resources are being deployed, however, on the cluster level and without the namespace.

Is it possible to deploy namespaced CRDs or not? The documentation says that the CRDs are cluster level which means no I guess, however, graph below the documentation shows the `namespace` value. In case we cannot deploy the namespaced CRDs, the graph could be a bit misleading.

Documentation I'm referring is [this](https://github.com/fluent/fluent-operator#fluent-bit).

Thanks in advance!

### How did you install fluent operator?

Installation was done via Helm.

**Comment by benjaminhuo** [comment]
@alternaivan `FluentBit` is namespaced CRD which controls the namespaced Fluent Bit Daemonset.
`ClusterInput`, `ClusterParser`, `ClusterFilter`, and `ClusterOutput` are all cluster-wide CRDs, this is because FluentBit is acting as a global agent to collect logs on each K8s node which requires cluster-wide privileges

**Comment by adiforluls** [comment]
We now have namespaced FluentBit CRDs in the operator starting v2.2.0.

**Comment by alternaivan** [comment]
Hi @adiforluls,

Thanks for the update. I've tested it on my local cluster, and although the CRDs such as Output are now namespaced it seems that the `kind: Output` is not working. I've tested it in parallel with both `kind: ClusterOutput` and `kind: Output`, the former is working, but the latter isn't. Am I missing something?

Below is both `Output` and `ClusterOutput` definitions.

```yaml
apiVersion: fluentbit.fluent.io/v1alpha2
kind: Output
metadata:
  labels:
    fluentbit.fluent.io/enabled: "true"
  name: es
  namespace: fluent
spec:
  es:
    bufferSize: 25M
    generateID: true
    host: "elasticsearch"
    index: fluent-bit-index
    logstashFormat: false
    port: 9200
    replaceDots: true
    timeKey: '@timestamp'
  matchRegex: (?:service)\.(.*)
```
...
```yaml
apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterOutput
metadata:
  labels:
    fluentbit.fluent.io/enabled: "true"
  name: es
spec:
  es:
    bufferSize: 25M
    generateID: true
    host: "elasticsearch"
    index: fluent-bit-index
    logstashFormat: false
    port: 9200
    replaceDots: true
    timeKey: '@timestamp'
  matchRegex: (?:service)\.(.*)
```

Thanks,
Marjan
