### ISSUE TITLE
bug: fluentd loki output plugin integration not conform to the plugin configuration

### ISSUE THREAD

**Issue by antrema** [fluent/fluent-operator#522]
### Describe the issue

The fluentd loki output plugin integration generate a fluentd configuration that doesn't fit the plugin configuration expectations.  
CRDs and operator wait for `host` and `port` parameters while plugin waits for `url`

### To Reproduce

Create a `ClusterOutput` as follow:

```yaml
apiVersion: fluentd.fluent.io/v1alpha1
kind: ClusterOutput
metadata:
  name: cluster-fluentd-output-loki
  labels:
    output.fluentd.fluent.io/scope: "antrema"
    output.fluentd.fluent.io/enabled: "true"
spec: 
  outputs: 
  - loki:
      host: "loki.loki.svc"
      port: 3100
```
This `ClusterOutput` is conform to the CRDs: `host` and `port` parameters are defined.
The generated configuration is as follow:

```
<source>
  @type  forward
  bind  0.0.0.0
  port  24224
</source>
<match **>
  @id  main
  @type  label_router
  <route>
    @label  @4a7489aeb8a1024f96f1cf69234e2764
    <match>
      namespaces  default,fluent,kube-system,loki
    </match>
  </route>
</match>
<label @4a7489aeb8a1024f96f1cf69234e2764>
  <match **>
    @id  ClusterFluentdConfig-cluster-cluster-fluentd-config::cluster::clusteroutput::cluster-fluentd-output-loki-0
    @type  loki
    host  loki.loki.svc
    port  3100
  </match>
</label>
```
While the fluentd-loki-output-plugin [documentation](https://grafana.com/docs/loki/latest/clients/fluentd/#usage) refers to
```
<match **>
  @type loki
  url "https://logs-prod-us-central1.grafana.net"
  username "#{ENV['LOKI_USERNAME']}"
  password "#{ENV['LOKI_PASSWORD']}"
  extra_labels {"env":"dev"}
  flush_interval 10s
  flush_at_shutdown true
  buffer_chunk_limit 1m
</match>
```

### Expected behavior

The CRD and operator should be conform to the plugin documentation, so should accept `url` parameter instead of `host` and `port`
The `ClusterOutput` definition will become:
```yaml
apiVersion: fluentd.fluent.io/v1alpha1
kind: ClusterOutput
metadata:
  name: cluster-fluentd-output-loki
  labels:
    output.fluentd.fluent.io/scope: "antrema"
    output.fluentd.fluent.io/enabled: "true"
spec: 
  outputs: 
  - loki:
      url: "http://loki.loki.svc:3100"
```

### Your Environment

```markdown
- Fluent Operator version: kubesphere/fluent-operator:v1.7.0; docker.io/kubesphere/fluent-operator@sha256:be402a3040b4eaec43157c4ac5126c038876eedd5d095db1a78da4ccbce6ced1
- Container Runtime: containerd://1.6.6-k3s1 
- Operating system: Linux/AMD64
- Kernel version: 5.4.0-135-generic
```

### How did you install fluent operator?

I installed the fluent-operator as described in fluent-operator [documentation](https://github.com/fluent/fluent-operator#deploy-fluent-operator-with-yaml)

```bash
kubectl create ns fluent 
kubectl apply -f https://raw.githubusercontent.com/fluent/fluent-operator/release-1.7/manifests/setup/setup.yaml
```
