### ISSUE TITLE
add dnsPolicy support to the FluentBit custom resource

### ISSUE THREAD

**Issue by dh185221** [fluent/fluent-operator#524]
### Is your feature request related to a problem? Please describe.

I'd like to use the `use_kubelet` option when configuring the kubernetes fliter plugin.  As noted in the [documentation](https://docs.fluentbit.io/manual/pipeline/filters/kubernetes#configuration-setup) you need to have a daemonset that uses 

```
hostNetwork: true
dnsPolicy: ClusterFirstWithHostNet
```

### Describe the solution you'd like

This request is to add support for `dnsPolicy` in the FluentBit custom resource.   That would let us create a FluentBit resource similar to this truncated version

```
apiVersion: fluentbit.fluent.io/v1alpha2
kind: FluentBit
metadata:
  name: fluent-bit
  labels:
    app.kubernetes.io/name: fluent-bit
spec:
  volumes:
  - name: journal
    hostPath:
      path: /var/log/journal
  - name: mnt
    hostPath:
      path: /mnt
  - name: varlibdockercontainers
    hostPath:
      path: /var/snap/microk8s/
  - name: varlog
    hostPath:
      path: /var/log
  tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
    operator: Exists
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
.
.
.
```

### Additional context

This would support https://github.com/fluent/fluent-operator/issues/514 but I think this could be done independently b/c if dnsPolicy is added then people could add a ClusterFilter with the customPlugin feature to include the kubernetes filter plugin
