### ISSUE TITLE
Support Dynamic Reload when an annotation is added to a service account 

### ISSUE THREAD

**Issue by HarleyB123** [fluent/fluent-operator#562]
### Is your feature request related to a problem? Please describe.

Using fluentbit, I am trying to get Cloudwatch to work as an output plugin. See below for a very basic configuration setup:

```
apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterInput
metadata:
  labels:
    fluentbit.fluent.io/component: logging
    fluentbit.fluent.io/enabled: "true"
  name: tail
spec:
  tail:
    db: /fluent-bit/tail/pos.db
    dbSync: Normal
    memBufLimit: 5MB
    parser: docker
    path: /var/log/containers/*.log
    refreshIntervalSeconds: 10
    skipLongLines: true
    tag: kube.*
---
apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterOutput
metadata:
  namespace: fluent
  name: cloudwatch-output
  labels:
    fluentbit.fluent.io/enabled: "true"
    fluentbit.fluent.io/mode: "fluentbit-only"
spec:
  customPlugin:
    config: |
      Name       cloudwatch_logs
      Match      kube.*
      region     <region>
      log_group_name  <name>
      log_stream_name <name>
```

I am also following option 3 (3. EKS Web Identity Token (OIDC)) as a method of authenticating to AWS as per the fluentbit documentation [here](https://github.com/fluent/fluent-bit-docs/blob/43c4fe134611da471e706b0edb2f9acd7cdfdbc3/administration/aws-credentials.md#3-eks-web-identity-token-oidc). This involves adding an annotation to the fluent-bit service account. 

When this annotation is added, I'd expect the fluentbit pods to be able to authenticate with Cloudwatch. However, I must first delete the fluentbit pod before the authentication and output plugin works as expected.

### Describe the solution you'd like

I'm unsure on if this will work, but does changing the `FluentBitSpec` cause the app to dynamically reload? If so, then setting some field such called `serviceAccountAnnotations` [here](https://github.com/fluent/fluent-operator/blob/master/docs/fluentbit.md#fluentbitspec) would solve the issue.
