### ISSUE TITLE
Namespaced FluentBit CRDs and configs

### ISSUE THREAD

**Issue by adiforluls** [fluent/fluent-operator#580]
### Is your feature request related to a problem? Please describe.

In #521 I raised the request for having namespaced FluentBit CRDs and configs. 

Following up on the discussion we had there, I don't think an external plugin is needed for namespace based multiple log routing in FluentBit daemonset. Namespace isolation of logs is a critical feature in my opinion. The two basic requirements being:

- A namespace admin/user should be able to create CRs to process logs coming out of their application namespace.
-  The CRs should not affect logs coming out of other namespaces (i.e. a malicious CR should not be able to gain unwanted access of logs coming out of other namespace).

For a k8s based input, I have a proposal to achieve namespace logging with FluentBit Daemonset.

### Describe the solution you'd like

The basic idea is to process the CR configs and mutate certain fields that make use of k8s metadata. Tags and match rules make the log routing possible in FluentBit, and for k8s based input (tail) tags hold k8s metadata in the form of <tag_prefix>.var.log.containers.<pod_name>_<namespace_name>_<container_name>.log. 

The proposal is to form a hash based on namespace name per namespace and add it to the tag as prefix. The match rule will also be mutated accordingly. For this task the rewrite_tag filter plugin will be used.

Below is the pseudo-code.

- Controller detects the namespaced resources. 

- Controller creates a rewrite_tag plugin filter config to mutate the tag for log records coming out of the target namespace to include hash of namespace as the tag prefix.

- The rewrite_tag filter config should be out of control of any user and will be handled by the operator (the user should not be able to mutate it).

- Mutate the match rule to add target namespace’s hash prefix. 

- Security:

  - Since the tag and match rules will be mutated to include the hashed namespace prefix by the operator, it's not possible for a user to create a malicious CR in another namespace since they can't set the prefix for tag and match that dictate the log routing for a namespace.

  - E.g.: If a malicious user creates a CR in namespace ns2 with a match rule h[ns1].*, the controller will mutate this match to h[ns2].h[ns1].*, so the user won't be able to get unwanted access to other namespace logs.

  - It might make sense to allow these tags and rules in Cluster level CRs though. 

- **Namespaced Parsers**:

  - Append the namespace hash to the parser name as a suffix in the actual FluentBit configs.

    - my-regex → my-regex-h[ns1]

  - Filters making use of parsers by name will be updated accordingly in the final config by the controller.

    - If the filter has specified a parser named my-regex, search for a parser with this name in the same namespace. If the parser exists, the parser section of the filter will be updated in the final fluentbit config to use my-regex-h[ns1] by the controller.

    - If it does not exist, then check if it's a Cluster level resource. Include this parser if it is, ignore/omit otherwise. 

Below is an example of the final rewrite_tag config to mutate the tag coming from namespace ns1 by the controller.
```
[FILTER]
    Name          rewrite_tag
    Match         kube.*.*_ns1_*.log
    Rule          $log "^.*\[ns1\].*$"  h[ns1].$TAG false
```
The requirement will be to make Filters, Outputs and Parsers to be namespaced at least. The below examples assumes input to be Cluster level.

Example CRs and corresponding FluentBit configs:
```
apiVersion: fluentbit.fluent.io/v1alpha2
kind: Filter
metadata:
  name: kubernetes
  namespace: ns1
  labels:
    fluentbit.fluent.io/enabled: "true"
    fluentbit.fluent.io/mode: "k8s"
spec:
  match: kube.*
  filters:
  - parser:
      keyName: log
      parser: my-regex
---
apiVersion: fluentbit.fluent.io/v1alpha2
kind: Output
metadata:
  name: ns1-output
  namespace: ns1
  labels:
    fluentbit.fluent.io/enabled: "true"
    fluentbit.fluent.io/mode: "k8s"
spec:
  match: kube.*
  openSearch:
  	host: foo.bar
	port: 9200
---
apiVersion: fluentbit.fluent.io/v1alpha2
kind: Parser
metadata:
  name: my-regex
  namespace: ns1
  labels:
    fluentbit.fluent.io/enabled: "true"
spec:
  regex:
    timeKey: time
    timeFormat: "%d/%b/%Y:%H:%M:%S %z"
    types: "code:integer size:integer"
    regex: '^(?<host>[^ ]*) [^ ]* (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^\"]*?)(?: +\S*)?)?" (?<code>[^ ]*) (?<size>[^ ]*)(?: "(?<referer>[^\"]*)" "(?<agent>[^\"]*)")?$'
```

```
[FILTER]
    Name parser
    Match h[ns1].kube.*
    Parser my_regex-h[ns1]
    KeyName log
 
[Output]
    Name opensearch
    Match h[ns1].kube.*
    Host foo.bar
    Port 9200
 
[PARSER]
    Name my-regex-h[ns1]
    TimeKey time
    TimeFormat "%d/%b/%Y:%H:%M:%S %z"
    Types "code:integer size:integer"
    Regex '^(?<host>[^ ]*) [^ ]* (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^\"]*?)(?: +\S*)?)?" (?<code>[^ ]*) (?<size>[^ ]*)(?: "(?<referer>[^\"]*)" "(?<agent>[^\"]*)")?$'
```

### Additional context

This is a possible approach/algorithm, we can definitely discuss, refine and enhance the idea. Suggestions are welcome.
I'm open to contribute and willing to make this enhancement if there's an agreement.
