### ISSUE TITLE
bug: `path` field required in CRD for buffer struct, but logs warm for memory buffer type in fluentd

### ISSUE THREAD

**Issue by antrema** [fluent/fluent-operator#581]
### Describe the issue

When creating a memory-type `buffer` section in Fluentd ClusterOutput, the field `Path` is required by CRD.  
Even if it has no effect on Fluentd, its specification creates a warm log entry in fluentd pod, each time it reconcile:  
```
2023-02-17 02:19:01 +0000 [warn]: parameter 'path' in <buffer $.loki-tenant>
  @type "memory"
  flush_interval 5s
  path /buffers/memory.log
</buffer> is not used.
```

### To Reproduce

Create a ClusterOutput, as follow:
```yaml
---
apiVersion: fluentd.fluent.io/v1alpha1
kind: ClusterOutput
metadata:
  name: fluentd-output-loki
  labels:
    output.fluentd.fluent.io/enabled: "true"
spec:
  outputs:
    - loki:
        url: http://loki-write.loki.svc:3100
        tenantID:
          valueFrom:
            secretKeyRef:
              key: tenant_key
              name: tenant-name
        labels:
        - cluster=linux-lab
      buffer:
        type: memory
        path: /buffers/memory.log
        tag: $.loki-tenant
        flushInterval: 5s
```
Have a look at fluentd logs

### Expected behavior

No warm log in fluentd pod

### Your Environment

```markdown
- Fluent Operator version: kubesphere/fluent-operator:v2.0.1@sha256:6c1ae07167ac51a426fa8bdd0bcc08456dadcfbd7ce4c67514a5ee28c2c1078d
- Container Runtime: containerd://1.6.15
- Operating system: Ubuntu 22.04.1 LTS
- Kernel version: 5.15.0-46-generic
```

### How did you install fluent operator?

I installed the fluent-operator as described in fluent-operator [documentation](https://github.com/fluent/fluent-operator#deploy-fluent-operator-with-yaml)
```
kubectl create ns fluent 
kubectl apply -f https://raw.githubusercontent.com/fluent/fluent-operator/release-2.0/manifests/setup/setup.yaml
```
