### ISSUE TITLE
bug: ClusterRole is missing "collectors" in "fluentbit.fluent.io" group in version 1.7.2

### ISSUE THREAD

**Issue by brint97** [fluent/fluent-operator#588]
### Describe the issue

The `fluentbit.fluent.io` group is missing a `collectors` entry in the `ClusterRole` definition for fluent-operator 1.7.2

Error log from the fluent-operator main container
```1 reflector.go:424] pkg/mod/k8s.io/client-go@v0.26.1/tools/cache/reflector.go:169: failed to list *v1alpha2.Collector: collectors.fluentbit.fluent.io is forbidden: User "system:serviceaccount:explorer:fluent-operator" cannot list resource "collectors" in API group "fluentbit.fluent.io" at the cluster scope```

### To Reproduce

Install the fluent-operator Helm Chart version 1.7.2

### Expected behavior

ClusterRole definition should contain the following section

``` yaml
# ...
- apiGroups:
  - fluentbit.fluent.io
  resources:
  - fluentbits
  - clusterfluentbitconfigs
  - clusterfilters
  - clusterinputs
  - clusteroutputs
  - clusterparsers
  - collectors # <-- add this line
# ...
```

### Your Environment

```markdown
- Fluent Operator version: 1.7.2
- Container Runtime: Docker
- Operating system: 
- Kernel version:
```

### How did you install fluent operator?

helm install
