### ISSUE TITLE
Does watchedNamespaces support regex

### ISSUE THREAD

**Issue by tanmx** [fluent/fluent-operator#589]
### Describe the issue

I want to use ClusterFluentdConfig to collect all logs of the cluster except logging namespace.
And use FluentdConfig in logging namespace to collect the namespace logs
If I have many namespaces and they are updated frequently, watchedNamespaces also need to be updated synchronously, which will be very troublesome. Is there any other good way?

ClusterFluentdConfig-> all namespace expect logging namespace-> ClusterOutput -> es(all)
FluentdConfig -> logging namespace-> output -> es(other)

### How did you install fluent operator?

```
helm upgrade --install --wait --create-namespace --namespace logging -f fluent-values.yaml fluent-operator fluent-operator
```
the fluent-values.yaml
```
fluentd:
  enable: true
  name: fluentd
  port: 24224
  image:
    repository: "kubesphere/fluentd"
    tag: "v1.15.3-arm64"
  replicas: 1
  forward:
    port: 24224
  watchedNamespaces:
    - kube-system
    - default
    - monitoring
  resources:
    limits:
      cpu: 1
      memory: 1024Mi
    requests:
      cpu: 100m
      memory: 128Mi
```
