### ISSUE TITLE
Make default ClusterInputs optional and configurable

### ISSUE THREAD

**Issue by AndreaVida** [fluent/fluent-operator#594]
### Is your feature request related to a problem? Please describe.

Currently it is not possible to opt out one of default ClusterInputs (tail or systemd) without disabling all default stuff  including fluentbit instance, by setting `Kubernetes ` value to false.

### Describe the solution you'd like

Make default ClusterInputs optional and configurable as already done for ClusterFilter objects, through Helm values like this:
```yaml
input:
    tail:
      enable: yes
      memBufLimit: 5MB
      path: /var/log/containers/*.log
   systemd:
     enable: false
     path: /var/log/journal
```
