### ISSUE TITLE
bug: Namespaced fluent-bit output CRDs and regex extracted custom tag with tail plugin

### ISSUE THREAD

**Issue by niwza-ua** [fluent/fluent-operator#689]
### Describe the issue

I want to use custom regex extracted tag with tail input plugin and then use this tag in namespaced `Output` CR match or match_Regex, but this doesn't work because of the wrong config is being generated.

### To Reproduce

Minimum fluent-operator helm based install and some additional CRs.
```
NAME           	NAMESPACE	REVISION	UPDATED                              	STATUS  	CHART                	APP VERSION
fluent-operator	fluent   	1       	2023-04-07 16:44:32.006192 +0300 EEST	deployed	fluent-operator-2.2.0	2.2.0
```
```
USER-SUPPLIED VALUES:
fluentbit:
  filter:
    containerd:
      enable: false
    kubernetes:
      enable: false
    systemd:
      enable: false
  input:
    systemd:
      enable: false
    tail:
      enable: false
```

Cluster level CRs
```
apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterInput
metadata:
  name: tail
  labels:
    fluentbit.fluent.io/enabled: "true"
    fluentbit.fluent.io/component: logging
spec:
  tail:
    tag: kube.<namespace_name>.<pod_name>.<container_name>.<docker_id>
    path: /var/log/containers/*.log
    refreshIntervalSeconds: 10
    parser: docker
    tagRegex: '(?<pod_name>[a-z0-9](?:[-a-z0-9]*[a-z0-9])?(?:\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)_(?<namespace_name>[^_]+)_(?<container_name>.+)-(?<docker_id>[a-z0-9]{64})\.log$'
    memBufLimit: 20Mb
    skipLongLines: true
    db: /fluent-bit/tail/pos.db
    dbSync: Normal
```
```
apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterFilter
metadata:
  labels:
    fluentbit.fluent.io/component: logging
    fluentbit.fluent.io/enabled: "true"
  name: kubernetes
spec:
  filters:
  - kubernetes:
      annotations: false
      k8sLoggingExclude: true
      keepLog: false
      kubeCAFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      kubeTagPrefix: kube.
      kubeTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      kubeURL: https://kubernetes.default.svc:443
      labels: false
      mergeLog: true
      regexParser: k8s-custom-tag
  - nest:
      addPrefix: kubernetes_
      nestedUnder: kubernetes
      operation: lift
  - modify:
      rules:
      - remove: stream
      - remove: kubernetes_pod_id
      - remove: kubernetes_host
      - remove: kubernetes_container_hash
  - nest:
      nestUnder: kubernetes
      operation: nest
      removePrefix: kubernetes_
      wildcard:
      - kubernetes_*
  match: kube.*
```
```
apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterParser
metadata:
  name: k8s-custom-tag
  labels:
    fluentbit.fluent.io/enabled: "true"
spec:
  regex:
    regex: '(?<namespace_name>[^_.]+)\.(?<pod_name>[a-z0-9](?:[-a-z0-9]*[a-z0-9])?(?:\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*+)\.(?<container_name>[^.]+)\.(?<docker_id>[a-z0-9]{64})$'
```

Namespaced CRs
```
apiVersion: fluentbit.fluent.io/v1alpha2
kind: FluentBitConfig
metadata:
  name: fluent-bit-config-foo
  namespace: foo
  labels:
    app.kubernetes.io/name: fluent-bit
spec:
  outputSelector:
    matchLabels:
      fluentbit.fluent.io/enabled: "true"
```
```
apiVersion: fluentbit.fluent.io/v1alpha2
kind: Output
metadata:
  name: stdout-output-foo
  namespace: foo
  labels:
    fluentbit.fluent.io/enabled: "true"
    fluentbit.fluent.io/component: logging
spec:
  matchRegex: ^kube\.foo\.(.)*$
  stdout: {}
```

The resulting config for `rewrite_tag` filter uses wrong match pattern and doesn't emit any records. And also when `matchRegex` is used the resulting regex in output plugin doesn't strip `^` anchor from the initial regex

generated config files:

**fluent-bit.conf**
```
[Service]
    Parsers_File    parsers.conf
[Input]
    Name    tail
    Path    /var/log/containers/*.log
    Refresh_Interval    10
    Skip_Long_Lines    true
    DB    /fluent-bit/tail/pos.db
    DB.Sync    Normal
    Mem_Buf_Limit    20Mb
    Parser    docker
    Tag    kube.<namespace_name>.<pod_name>.<container_name>.<docker_id>
    Tag_Regex    (?<pod_name>[a-z0-9](?:[-a-z0-9]*[a-z0-9])?(?:\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)_(?<namespace_name>[^_]+)_(?<container_name>.+)-(?<docker_id>[a-z0-9]{64})\.log$
[Filter]
    Name    kubernetes
    Match    kube.*
    Kube_URL    https://kubernetes.default.svc:443
    Kube_CA_File    /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    Kube_Token_File    /var/run/secrets/kubernetes.io/serviceaccount/token
    Kube_Tag_Prefix    kube.
    Merge_Log    true
    Keep_Log    false
    Regex_Parser    k8s-custom-tag
    K8S-Logging.Exclude    true
    Labels    false
    Annotations    false
[Filter]
    Name    nest
    Match    kube.*
    Operation    lift
    Nested_under    kubernetes
    Add_prefix    kubernetes_
[Filter]
    Name    modify
    Match    kube.*
    Remove    stream
    Remove    kubernetes_pod_id
    Remove    kubernetes_host
    Remove    kubernetes_container_hash
[Filter]
    Name    nest
    Match    kube.*
    Operation    nest
    Wildcard    kubernetes_*
    Nest_under    kubernetes
    Remove_prefix    kubernetes_
[Filter]
    Name    rewrite_tag
    Match    kube.<namespace_name>.<pod_name>.<container_name>.<docker_id>
    Rule    $kubernetes['namespace_name'] ^(foo)$ ac8be4aee61f5f6e21b8c5afffb52939.$TAG false
    Emitter_Name    re_emitted_ac8be4aee61f5f6e21b8c5afffb52939
[Output]
    Name    stdout
    Match_Regex    ^ac8be4aee61f5f6e21b8c5afffb52939\.^kube\.foo\.(.)*$
```

### Expected behavior

I expect that resulting filter and output configuration matches given tag or tag regex and logs are routed to the desired output.

### Your Environment

```markdown
- Fluent Operator version: 2.2.0
- Container Runtime: docker
- Operating system: "Amazon Linux 2"
- Kernel version: 5.4.231-137.341.amzn2.x86_64
```

### How did you install fluent operator?

`helm upgrade --install fluent-operator ./charts/fluent-operator -n fluent -f <custom-values>.yaml`

### Additional context

None
