### ISSUE TITLE
bug: latest fluent-operator release not synced with official helm repo

### ISSUE THREAD

**Issue by felfa01** [fluent/fluent-operator#694]
### Describe the issue

When running helm dependency update with updated Chart.yaml file with 2.2.0 I get the following error `can't get a valid version for repositories fluent-operator. Try changing the version constraint in Chart.yaml`

``` yaml
  - name: fluent-operator
    version: 2.2.0
    repository: https://fluent.github.io/helm-charts
```

Please sync the latest charts to the official repo whenever a new fluent operator version is released.

### To Reproduce

Run helm dependency update

### Expected behavior

2.2.0 fluent operator files is downloaded to local environment

### Your Environment

```markdown
- Fluent Operator version: 2.2.0
- Container Runtime:
- Operating system:
- Kernel version:
```
