### ISSUE TITLE
Add feature to add multilineParser in helm chart, when enable kubernetes: true

### ISSUE THREAD

**Issue by allanian** [fluent/fluent-operator#733]
### Is your feature request related to a problem? Please describe.

Hello,
I'm getting some logs in json log format and its not parsed.

my values.yaml for helm chart
```
        containerRuntime: containerd
        Kubernetes: true
        fluentbit:
          crdsEnable: true
          enable: true
          image:
            repository: "kubesphere/fluent-bit"
            tag: "v2.1.2"
          input:
            tail:
              enable: true
              refreshIntervalSeconds: 10
              memBufLimit: 5MB
              path: "/var/log/containers/*.log"
              skipLongLines: true
```

### Describe the solution you'd like

can we add 1 option to helm chart, when it defined, like 
```
fluentbit.input.tail.multilineParser: docker, cri
```
