### ISSUE TITLE
bug: [Fluentd] ClusterFilter - 'reserve_data' parameter is required but nil is specified

### ISSUE THREAD

**Issue by xolott** [fluent/fluent-operator#741]
### Describe the issue

Creating a ClusterFilter for fluentd crashes the fluentd pod with `'reserve_data' parameter is required but nil is specified`

### To Reproduce

Create a ClusterFilter for fluentd

```yaml
apiVersion: fluentd.fluent.io/v1alpha1
kind: ClusterFilter
metadata:
  name: transform-log
  labels:
    app.kubernetes.io/name: fluentd
    filter.fluentd.fluent.io/scope: "cluster"
    filter.fluentd.fluent.io/enabled: "true"
spec:
  filters:
    - parser:
        keyName: "log"
        reserveData: true
        reserveTime: true
        parse:
          type: json
```

This is rendered as:

```
<filter **>
  @id ClusterFluentdConfig-cluster-cluster-fluentd-config::cluster::clusterfilter::transform-log-0
  @type parser
  key_name "0xc000c2bd60"
  reserve_data 0xc001333300
  reserve_time 0xc0013332ef
  <parse>
    @type json
  </parse>
</filter>
```

### Expected behavior

It should work as expected. At least reserve_data should be true or false, not an hexadecimal number

### Your Environment

```markdown
- Fluent Operator version: 2.2.0
- Container Runtime: containerd (AKS) - containerd://1.6.18+azure-1
- Operating system: based on AKS ubuntu distribution (AKSUbuntu-2204gen2containerd-202304.20.0
)
- Kernel version:
```

### How did you install fluent operator?

Using the helm chart `fluent-operator`, setting `Kubernetes` to `false`
