### ISSUE TITLE
bug: Fluentbit template volumes

### ISSUE THREAD

**Issue by kaiohenricunha** [fluent/fluent-operator#766]
### Describe the issue

The fluentbit template and values.yaml contain volume configuration that is not mirrored in the fluentbit crd.

So, this definition:

```
apiVersion: fluentbit.fluent.io/v1alpha2
kind: FluentBit
metadata:
  labels:
    app.kubernetes.io/name: fluent-bit
  name: fluent-bit
  namespace: fluent-system
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node-role.kubernetes.io/edge
            operator: DoesNotExist
  fluentBitConfigName: fluent-bit-config
  image: kubesphere/fluent-bit:v2.0.11
  imagePullSecrets:
    - name: image-pull-secret
  positionDB:
    hostPath:
      path: /var/lib/fluent-bit/
  resources:
    limits:
      cpu: ${FLUENTBIT_CPU_LIMIT:=500m}
      memory: ${FLUENTBIT_MEMORY_LIMIT:=200Mi}
    requests:
      cpu: ${FLUENTBIT_CPU_REQUEST:=10m}
      memory: ${FLUENTBIT_MEMORY_REQUEST:=25Mi}
  tolerations:
  - operator: Exists
  annotations:
    fluentbit.io/exclude: "true" # Exclude fluentbit logs from being collected by itself
  volumes:
  - name: certs-volume
    secret:
      secretName: selfsigned-certificate
  volumeMounts:
  - name: certs-volume
    mountPath: /etc/fluentbit/certs
```

Ends up generating this error:

```
flux2-system   fluent-agents                  9d    False     FluentBit/fluent-system/fluent-bit dry-run failed, error: failed to create typed patch object (fluent-system/fluent-bit; fluentbit.fluent.io/v1alpha2, Kind=FluentBit): .spec.volumeMounts: field not declared in schema...
```

### To Reproduce

Try to apply a fluentbit CR with volume and volumeMounts under spec.

or

Define additionalVolumes and additionalVolumeMounts in the values.yaml.

### Expected behavior

Being able to define custom volumes in fluentbit.

### Your Environment

```markdown
- Fluent Operator version: 2.2.0
- Container Runtime: Docker
- Operating system: Ubuntu
- Kernel version:
```

### How did you install fluent operator?

Via Helm chart.
