### ISSUE TITLE
bug: Parser - TimeFormat is written to time_type

### ISSUE THREAD

**Issue by Jakob3xD** [fluent/fluent-operator#778]
### Describe the issue

I tried adding a parser as filter using timeType and timeFormat to parse the time out of my logs.
Unfortunately the operator writes the timeFormat value as `time_type` to the config.

https://github.com/fluent/fluent-operator/blob/15478961c1fc0ba5e1760f826faf386b094468b0/apis/fluentd/v1alpha1/plugins/common/common_types.go#L201-L203

### To Reproduce

Use a filter like following:
```
---
apiVersion: fluentd.fluent.io/v1alpha1
kind: Filter
metadata:
  name: xyz
  labels:
    filter.fluentd.fluent.io/enabled: "true"
spec:
  filters:
    - parser:
        keyName: log
        parse:
          type: json
          timeType: '*string'
          timeFormat: '%FT%TZ'
```

Ends up like:
```
<parse>
  @type "json"
  time_type %FT%TZ
</parse>
```

### Expected behavior

The fluentd config should set the filed as `time_format` and not as `time_type`.

### Your Environment

```markdown
- Fluent Operator version: 2.3.0
- Container Runtime: containerd
- Operating system: Ubuntu 22.04
```
