### ISSUE TITLE
bug: TimeType wants *string instead of string

### ISSUE THREAD

**Issue by Jakob3xD** [fluent/fluent-operator#781]
### Describe the issue

K8S validation prevents users from setting `time_type` to string. It allows `*string` instead.
This results in fluentd crashing with following log line:
```
2023-06-07 11:36:40 +0000 [error]: config error file="/fluentd/etc/fluent.conf" error_class=Fluent::ConfigError error="valid options are string,unixtime,float,mixed but got *string"
```

### To Reproduce

Apply following filter:
```
---
apiVersion: fluentd.fluent.io/v1alpha1
kind: Filter
metadata:
  name: xyz
  labels:
    filter.fluentd.fluent.io/enabled: "true"
spec:
  filters:
    - parser:
        keyName: log
        parse:
          type: json
          timeType: '*string'
          utc: true

```

When setting timeType to the value `string` the validation fails with following line:
```
The Filter "xyz" is invalid: spec.filters[0].parser.parse.timeType: Unsupported value: "string": supported values: "float", "unixtime", "*string", "mixed"
```

### Expected behavior

The k8s validation should allow string instead of *string.

### Your Environment

```markdown
- Fluent Operator version:
- Container Runtime:
- Operating system:
- Kernel version:
```
