### ISSUE TITLE
help request: Logstash_Prefix_Separator

### ISSUE THREAD

**Issue by buxiaomo** [fluent/fluent-operator#807]
### Describe the issue

how can I use Logstash_Prefix_Separator on fluentbit ClusterOutput

### How did you install fluent operator?

helm

**Comment by buxiaomo** [comment]
my ClusterOutput
```
...
spec:
  es: 
    host: 172.16.2.11
    port: 9200
    logstashFormat: true
    logstashPrefix: demo2-noprod
```

this output index is `demo2-noprod-2023.06.21`, I want index is `demo2-noprod_2023.06.21`
