### ISSUE TITLE
feature: add serviceAccountAnnotations to FluentBit resource in Helm chart

### ISSUE THREAD

**Issue by sharkeyl** [fluent/fluent-operator#897]
### Is your feature request related to a problem? Please describe.

We're deploying the fluent-operator, and corresponding FluentBit resource, on an AWS EKS cluster. As we are using IAM Roles for Service Accounts, we need the ability to add the below annotation to the service account to provide the fluent-bit Pods with access to push to our log sink:

```yaml
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/fluent-bit-role
```

Without this, we see the follow error messages in the fluent-bit Pods:

```
[2023/08/25 12:41:41] [error] [aws_credentials] STS assume role request failed
[2023/08/25 12:41:41] [ warn] [aws_credentials] No cached credentials are available and a credential refresh is already in progress. The current co-routine will retry.
```

### Describe the solution you'd like

I've raised a PR to address the issue in both the fluent/fluent-operator and the fluent/helm-charts:

- fluent/fluent-operator: https://github.com/fluent/fluent-operator/pull/898
- fluent/helm-charts: https://github.com/fluent/helm-charts/pull/414

### To reproduce

You'll need an AWS IAM role with a trust relationship that the fluent-bit Pods can assume via [IRSA](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html).

I've installed the Helm chart from thelocal chart directory, i.e. `helm-charts/charts/fluent-operator`, using the following command: 

```bash
helm upgrade --install --namespace kube-system fluent-operator . --values local-values.yaml
```

Where the `local-values.yaml` file contains:

```yaml
namespaceOverride: kube-system
containerRuntime: containerd
operator:
  disableComponentControllers: fluentd
fluentbit:
  serviceAccountAnnotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::781632261136:role/dev-aws-for-fluent-bit-access
fluentd:
  crdsEnable: false
```
