### ISSUE TITLE
fluentbit daemonset without hostPath volumes

### ISSUE THREAD

**Issue by OlegVanHorst** [fluent/fluent-operator#907]
### Is your feature request related to a problem? Please describe.

The fluent-operator always creates hostPath volumes for the fluentbit daemonsets. Additional volumes are only appended.

We use k8s-as-a-service and our provider does not allow creating pods with hostPath volumes. But we can mount the node logs via a given persistentVolume (ReadOnlyMany).
We would like to add more flexibility to the volume handling. For example to use persistentVolumeClaim instead of hostPath.

### Describe the solution you'd like

This could be done by either a feature toggle to disable the hostPath volumes (varlibcontainers, varlogs, systemd) or switch to persistentVolumeClaim.

Or by overwriting all volumes with the ones in the FluentBit CR.

### Additional context

PersistentVolume to mount host logs:
```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/bound-by-controller: "yes"
  finalizers:
  - kubernetes.io/pv-protection
  name: host-logs
spec:
  accessModes:
  - ReadOnlyMany
  capacity:
    storage: "1"
  hostPath:
    path: /var/log
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  volumeMode: Filesystem
```
