### ISSUE TITLE
help request: 

### ISSUE THREAD

**Issue by rmechi** [fluent/fluent-operator#943]
### Describe the issue

- create output for `namespace-a` and everything else under `spec.outputs` exist ( ex. roles ) and valid. no issues when fluentd reload . everything look good.

```yaml
apiVersion: fluentd.fluent.io/v1alpha1
kind: Output
metadata:
  namespace: namespace-a
  labels:
    xyz.developergitops.com/instance: namespace-a-logging
    output.fluentd.fluent.io/enabled: 'true'
    output.fluentd.fluent.io/scope: namespace
spec:
  outputs:
    - cloudWatch:
        webIdentityTokenFile: /var/run/secrets/eks.amazonaws.com/serviceaccount/token
        logGroupName:namespace-a-group
        roleArn: arn:aws:iam::123456789:role/hub-role
        awsUseSts: true
        includeTimeKey: true
        autoCreateStream: true
        roleSessionName: namespace-a_session
        logStreamName: namespace-a-stream
        awsStsRoleArn: 'arn:aws:iam::987654321:role/spoke-role'
        region: us-east-1
        maxEventsPerBatch: '10000'
```

- create output for `namespace-c` , `namespace-d`, `namespace-e` and everything else under `spec.outputs` exist ( ex. roles ) and valid. no issues when fluentd reload . everything look good.

- Now, create output for `namespace-f` with non existing role.

```yaml
apiVersion: fluentd.fluent.io/v1alpha1
kind: Output
metadata:
  namespace: namespace-f
  labels:
    xyz.developergitops.com/instance: namespace-f-logging
    output.fluentd.fluent.io/enabled: 'true'
    output.fluentd.fluent.io/scope: namespace
spec:
  outputs:
    - cloudWatch:
        webIdentityTokenFile: /var/run/secrets/eks.amazonaws.com/serviceaccount/token
        logGroupName:namespace-f-group
        roleArn: arn:aws:iam::757575757:role/hub-role
        awsUseSts: true
        includeTimeKey: true
        autoCreateStream: true
        roleSessionName: namespace-f_session
        logStreamName: namespace-f-stream
        awsStsRoleArn: 'arn:aws:iam::74658383:role/spoke-role'
        region: us-east-1
        maxEventsPerBatch: '10000'
```

Now, role mentioned under `awsStsRoleArn` not exist. when **fluentd** reloads
  -> fluent bit throuw `TCP connection failed: fluentd.fluent.svc.cluster.local:24224 (Connection refused)`
  ->  fluentd throw something like 
`_class=Aws::STS::Errors::AccessDenied error="User: arn:aws:sts::757575757:assumed-role/hub-role/NjVmNTJkNjUtYTFkMC00MzY1LWJhNjctN2M1MWZmMmY1Mjhl is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::74658383::role/spoke-role"`

after creating `Output` for `namespace-f` with non existing role. **fluentd**  started refusing connections impacting whole cluster i.e. all other namespaces those have valid configurations through `Output` object. 

**any why to ignore or not process the `outputs` those have non woking configuration ?** ex. role not exist or target not listening etc.  because one non working `output` object impact thousands of other namespace logging those have valid `Output` configuration as i see one not working `Output` leading `fluentd` pod to refuse the connection.
