### ISSUE TITLE
bug: ClusterFluentBitConfig is missing a parserSelector

### ISSUE THREAD

**Issue by JoeDerby** [fluent/fluent-operator#955]
### Describe the issue

ClusterFluentBitConfig in the [helm chart](https://github.com/fluent/fluent-operator/blob/master/charts/fluent-operator/templates/fluentbitconfig-fluentBitConfig.yaml) is missing a 'parserSelector' so unable to add custom Parser using the label.

```
{{- if .Values.Kubernetes -}}
{{- if .Values.fluentbit.enable -}}
apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterFluentBitConfig
metadata:
  name: fluent-bit-config
  labels:
    app.kubernetes.io/name: fluent-bit
spec:
  service:
    parsersFile: parsers.conf
    httpServer: true
{{- if .Values.fluentbit.service.storage }}
    storage:
{{ toYaml .Values.fluentbit.service.storage | indent 6 }}
{{- end }}
  inputSelector:
    matchLabels:
      fluentbit.fluent.io/enabled: "true"
  filterSelector:
    matchLabels:
      fluentbit.fluent.io/enabled: "true"
  outputSelector:
    matchLabels:
      fluentbit.fluent.io/enabled: "true"
{{- end }}
{{- end }}
```

### To Reproduce

creation of the following ClusterParser would not get picked up by the fluent operator for the fluentbitconfig due to the missing parserSelector label match.

```apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterParser
metadata:
  name: cri-time
  labels:
    fluentbit.fluent.io/enabled: "true"
spec:
  regex:
    timeKey: time
    timeFormat: "%Y-%m-%dT%H:%M:%S.%L%z"
    timeKeep: true
    regex: '^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<logtag>[^ ]*) (?<message>.*)$
```

### Expected behavior

I would expect the same label `fluentbit.fluent.io/enabled: "true"` to work with a Parser resource the same way it does with the other custom resources.

### How did you install fluent operator?

via the helm chart
